---
version: 2
plugins:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-0-54
exclude_patterns:
- script/
- spec/
