---
require: rubocop-rspec
inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.2
  DisplayCopNames: true
  Exclude:
    - gemfiles/**/*
    - tmp/**/*

Layout/DotPosition:
  EnforcedStyle: leading
  Enabled: true

Layout/ExtraSpacing:
  Enabled: true

Lint/LiteralInInterpolation:
  AutoCorrect: true

Metrics/BlockLength:
  CountComments: false  # count full line comments?
  Exclude:
    - '**/*_spec.rb'

Metrics/LineLength:
  Max: 120
  Enabled: true

Naming/FileName:
  Enabled: true

Style/ClassAndModuleChildren:
  EnforcedStyle: nested
  Enabled: true

Style/Documentation:
  Enabled: false

Style/MixinGrouping:
  Exclude:
    - spec/**/*.rb

Style/ModuleFunction:
  EnforcedStyle: extend_self # Allows us to have private methods too

Style/PercentLiteralDelimiters:
  # Hound and CodeClimate are currently using an old version of Rubocop with
  # different defaults, so we set them explicitly here.
  PreferredDelimiters:
    default: ()
    '%i': '[]'
    '%I': '[]'
    '%r': '{}'
    '%w': '[]'
    '%W': '[]'

Style/StringLiterals:
  EnforcedStyle: single_quotes
  Enabled: true
