---
language: ruby

rvm:
  - ruby-head
  - 2.4.1
  - 2.3.4
  - 2.2.6
  - 2.1.10

gemfile:
  - gemfiles/4.2.gemfile
  - gemfiles/5.0.gemfile
  - gemfiles/5.1.gemfile

branches:
  only:
    - master

matrix:
  allow_failures:
    - rvm: ruby-head
