---
language: ruby

rvm:
  - ruby-head
  - 2.5.1
  - 2.4.1
  - 2.3.4
  - 2.2.6

gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile

matrix:
  allow_failures:
    - rvm: ruby-head

before_install:
  - gem update bundler

after_success:
  - bundle exec codeclimate-test-reporter
